apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: backstage-example-template
spec:
  type: service
  lifecycle: production
  system: internal-dev-portal
  owner: user:default/ilkaykisayol

  parameters:
    - title: Fill The Steps
      properties:
        owner:
          type: string
          ui:field: OwnerPicker
        appVersion:
          title: Application Version
          type: string
          description: Version of application
          default: 'Boost 1.2'
          enum:
            - 'Boost 1.1'
            - 'Boost 1.2'
        ttl:
          title: Time To Live
          type: string
          default: '2 weeks'
          enum:
            - '1 week'
            - '2 weeks'
            - '4 weeks'
            - '8 weeks'
            - '10 weeks'
          enumNames:
            - 1 Week
            - 2 Weeks
            - 4 Weeks
            - 8 Weeks
            - 10 Weeks

  steps:
    - action: github:actions:dispatch
      id: trigger-build
      name: Trigger Build
      input:
        repoUrl: 'github.com?repo=pocboost&owner=ilkaykisayol'
        workflowId: 'pipeline_devops_env_request.yml'
        branchOrTagName: 'main'
        workflowInputs:
          owner: ${{ parameters.owner }}
          version: ${{ parameters.appVersion }}
          retention: ${{ parameters.ttl }}

  output:
    links:
      - title: README
        url: https://github.com/RDIT-DPS/devops-platform-documentation/blob/feature-docs-security-lifecycle-management/docs/design/ondemand-environment-devops-engineer.md
